name: Terraform Apply Cron Daily

on:
  schedule:
    - cron: '0 0 * * *' # Midnight UTC. Must match with destroy
    - cron: '0 12 * * *'
  push:
    tags:
      - daily_apply

jobs:
  apply:
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      subfolder: "daily"
    secrets: inherit
