name: Terraform Apply Cron Daily

on:
  schedule:
    - cron: '22 3 * * *' # 3:22 UTC. Must match with destroy
    - cron: '22 15 * * *'
  push:
    tags:
      - daily_apply

jobs:
  apply:
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      subfolder: "daily"
    secrets: inherit
