name: Terraform Destroy Cron

on:
  schedule:
    - cron: '0 1 * * *' # Must match with apply +1h
    - cron: '0 7 * * *' # Must match with apply +1h
  push:
    tags:
      - daily_destroy

jobs:
  destroy:
    uses: ./.github/workflows/terraform-destroy.yaml
    with:
      subfolder: "daily"
    secrets: inherit
