name: "Setup"

on:
  workflow_call:
    inputs:
      subfolder:
        type: string
        required: true
    outputs:
      workspaces:
        description: "List of workspaces"
        value: ${{ jobs.list-workspaces.outputs.workspaces }}

jobs:
  # Source: https://code.dblock.org/2021/09/03/generating-task-matrix-by-looping-over-repo-files-with-github-actions.html
  list-workspaces:
    runs-on: [self-hosted]
    outputs:
      workspaces: ${{ steps.set-matrix.outputs.workspaces }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: echo "workspaces=$(ls workspace/${{ inputs.subfolder }}/*/ -d | cut -f3 -d'/' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
