name: Terraform Apply Staging

on:
  push:
    tags:
      - apply

jobs:
  apply-staging-daily:
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      opensearch_index: "staging"
      subfolder: "daily"
    secrets: inherit
