name: Terraform Apply Staging

on:
  push:
    tags:
      - destroy

jobs:
  destroy-staging:
    uses: ./.github/workflows/terraform-destroy.yaml
    with:
      subfolder: "daily"
    secrets: inherit
