name: Terraform Destroy

on:
  workflow_call:

env:
  TF_CLOUD_ORGANIZATION: "${{ vars.TF_CLOUD_ORGANIZATION }}"
  TF_API_TOKEN: "${{ secrets.TERRAFORM_CLOUD_TOKEN }}"

jobs:
  setup:
    uses: ./.github/workflows/setup.yaml
  terraform:
    name: "Terraform Destroy"
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        workspace: ${{ fromJson(needs.setup.outputs.workspaces) }}
    env:
      TF_WORKSPACE: "${{ matrix.workspace }}"
      CONFIG_DIRECTORY: "./workspace/${{  matrix.workspace }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Destroy last Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.0
        id: destroy-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          is_destroy: true
      - name: Apply
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.0
        if: fromJSON(steps.destroy-run.outputs.payload).data.attributes.actions.IsConfirmable
        id: apply
        with:
          run: ${{ steps.destroy-run.outputs.run_id }}
          comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"
