name: Terraform Apply

on:
  workflow_call:
    inputs:
      opensearch_index:
        type: string
        default: "${{ vars.OPENSEARCH_INDEX }}"
        required: false

env:
  TF_CLOUD_ORGANIZATION: "${{ vars.TF_CLOUD_ORGANIZATION }}"
  TF_API_TOKEN: "${{ secrets.TERRAFORM_CLOUD_TOKEN }}"
  OPENSEARCH_PASSWORD: "${{ secrets.OPENSEARCH_PASSWORD }}"
  OPENSEARCH_USERNAME: "${{ vars.OPENSEARCH_USERNAME }}"
  OPENSEARCH_URL: "${{ vars.OPENSEARCH_URL }}"
  OPENSEARCH_INDEX: "${{ inputs.opensearch_index }}"

jobs:
  setup:
    uses: ./.github/workflows/setup.yaml
  terraform:
    name: "Terraform Apply"
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        workspace: ${{ fromJson(needs.setup.outputs.workspaces) }}
    env:
      TF_WORKSPACE: "${{ matrix.workspace }}"
      CONFIG_DIRECTORY: "./workspace/${{  matrix.workspace }}"
      RUN_ID: "${{ github.run_id }}_${{ matrix.workspace }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: envsubst
        uses: danielr1996/envsubst-action@1.0.0
        with:
          input: "${{ env.CONFIG_DIRECTORY }}/../hieradata.template.yaml"
          output: "${{ env.CONFIG_DIRECTORY }}/hieradata.yaml"
      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: apply-upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}

      - name: Create Apply Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        id: apply-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}
      - name: Apply
        uses: ./.github/workflows/apply
        if: fromJSON(steps.apply-run.outputs.payload).data.attributes.actions.IsConfirmable
        id: apply
        with:
          run: ${{ steps.apply-run.outputs.run_id }}
          comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"
      - name: Upload elasticsearch
        if: fromJSON(steps.apply-run.outputs.payload).data.attributes.actions.IsConfirmable && always()
        run: ./scripts/push_elasticsearch.sh
