name: Test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set delay time
        id: delay
        run: echo "time=$(date -u +"%Y-%m-%dT%H:%M:%SZ" -d "+1 minute")"

      - name: Run delayed job
        if: github.event_name == 'schedule' && github.event.schedule == 'cron'
        uses: actions/checkout@v3
      - name: Delayed job echo
        if: github.event_name == 'schedule' && github.event.schedule == 'cron'
        run: echo "This is the delayed job."

